package com.hlc.codeanalyzesystem.dao;

import com.hlc.codeanalyzesystem.entity.Fileresult;
import com.hlc.codeanalyzesystem.entity.FileresultExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
@Mapper
public interface FileresultDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileresult
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    long countByExample(FileresultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileresult
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    int deleteByExample(FileresultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileresult
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileresult
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    int insert(Fileresult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileresult
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    int insertSelective(Fileresult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileresult
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    List<Fileresult> selectByExampleWithBLOBs(FileresultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileresult
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    List<Fileresult> selectByExample(FileresultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileresult
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    Fileresult selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileresult
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    int updateByExampleSelective(@Param("record") Fileresult record, @Param("example") FileresultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileresult
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") Fileresult record, @Param("example") FileresultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileresult
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    int updateByExample(@Param("record") Fileresult record, @Param("example") FileresultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileresult
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    int updateByPrimaryKeySelective(Fileresult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileresult
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(Fileresult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileresult
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    int updateByPrimaryKey(Fileresult record);
}