package com.hlc.codeanalyzesystem.dao;

import com.hlc.codeanalyzesystem.entity.Projectresult;
import com.hlc.codeanalyzesystem.entity.ProjectresultExample;
import com.hlc.codeanalyzesystem.entity.ProjectresultWithBLOBs;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface ProjectresultDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectresult
     *
     * @mbg.generated Wed Mar 09 17:38:48 CST 2022
     */
    long countByExample(ProjectresultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectresult
     *
     * @mbg.generated Wed Mar 09 17:38:48 CST 2022
     */
    int deleteByExample(ProjectresultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectresult
     *
     * @mbg.generated Wed Mar 09 17:38:48 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectresult
     *
     * @mbg.generated Wed Mar 09 17:38:48 CST 2022
     */
    int insert(ProjectresultWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectresult
     *
     * @mbg.generated Wed Mar 09 17:38:48 CST 2022
     */
    int insertSelective(ProjectresultWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectresult
     *
     * @mbg.generated Wed Mar 09 17:38:48 CST 2022
     */
    List<ProjectresultWithBLOBs> selectByExampleWithBLOBs(ProjectresultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectresult
     *
     * @mbg.generated Wed Mar 09 17:38:48 CST 2022
     */
    List<Projectresult> selectByExample(ProjectresultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectresult
     *
     * @mbg.generated Wed Mar 09 17:38:48 CST 2022
     */
    ProjectresultWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectresult
     *
     * @mbg.generated Wed Mar 09 17:38:48 CST 2022
     */
    int updateByExampleSelective(@Param("record") ProjectresultWithBLOBs record, @Param("example") ProjectresultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectresult
     *
     * @mbg.generated Wed Mar 09 17:38:48 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") ProjectresultWithBLOBs record, @Param("example") ProjectresultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectresult
     *
     * @mbg.generated Wed Mar 09 17:38:48 CST 2022
     */
    int updateByExample(@Param("record") Projectresult record, @Param("example") ProjectresultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectresult
     *
     * @mbg.generated Wed Mar 09 17:38:48 CST 2022
     */
    int updateByPrimaryKeySelective(ProjectresultWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectresult
     *
     * @mbg.generated Wed Mar 09 17:38:48 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(ProjectresultWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectresult
     *
     * @mbg.generated Wed Mar 09 17:38:48 CST 2022
     */
    int updateByPrimaryKey(Projectresult record);
}