package com.hlc.codeanalyzesystem.entities;

import java.util.Date;

public class Project {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.id
     *
     * @mbg.generated Wed Feb 23 13:09:29 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.projectName
     *
     * @mbg.generated Wed Feb 23 13:09:29 CST 2022
     */
    private String projectname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.uploadDate
     *
     * @mbg.generated Wed Feb 23 13:09:29 CST 2022
     */
    private Date uploaddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.userId
     *
     * @mbg.generated Wed Feb 23 13:09:29 CST 2022
     */
    private Integer userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.id
     *
     * @return the value of project.id
     *
     * @mbg.generated Wed Feb 23 13:09:29 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.id
     *
     * @param id the value for project.id
     *
     * @mbg.generated Wed Feb 23 13:09:29 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.projectName
     *
     * @return the value of project.projectName
     *
     * @mbg.generated Wed Feb 23 13:09:29 CST 2022
     */
    public String getProjectname() {
        return projectname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.projectName
     *
     * @param projectname the value for project.projectName
     *
     * @mbg.generated Wed Feb 23 13:09:29 CST 2022
     */
    public void setProjectname(String projectname) {
        this.projectname = projectname == null ? null : projectname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.uploadDate
     *
     * @return the value of project.uploadDate
     *
     * @mbg.generated Wed Feb 23 13:09:29 CST 2022
     */
    public Date getUploaddate() {
        return uploaddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.uploadDate
     *
     * @param uploaddate the value for project.uploadDate
     *
     * @mbg.generated Wed Feb 23 13:09:29 CST 2022
     */
    public void setUploaddate(Date uploaddate) {
        this.uploaddate = uploaddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.userId
     *
     * @return the value of project.userId
     *
     * @mbg.generated Wed Feb 23 13:09:29 CST 2022
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.userId
     *
     * @param userid the value for project.userId
     *
     * @mbg.generated Wed Feb 23 13:09:29 CST 2022
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
}