package com.hlc.codeanalyzesystem.entities;

import java.util.Date;

public class Record {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.id
     *
     * @mbg.generated Wed Feb 23 16:56:04 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.userId
     *
     * @mbg.generated Wed Feb 23 16:56:04 CST 2022
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.projectId
     *
     * @mbg.generated Wed Feb 23 16:56:04 CST 2022
     */
    private Integer projectid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.operation
     *
     * @mbg.generated Wed Feb 23 16:56:04 CST 2022
     */
    private String operation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.operateDate
     *
     * @mbg.generated Wed Feb 23 16:56:04 CST 2022
     */
    private Date operatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.operateResult
     *
     * @mbg.generated Wed Feb 23 16:56:04 CST 2022
     */
    private String operateresult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.fileName
     *
     * @mbg.generated Wed Feb 23 16:56:04 CST 2022
     */
    private String filename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.id
     *
     * @return the value of record.id
     *
     * @mbg.generated Wed Feb 23 16:56:04 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.id
     *
     * @param id the value for record.id
     *
     * @mbg.generated Wed Feb 23 16:56:04 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.userId
     *
     * @return the value of record.userId
     *
     * @mbg.generated Wed Feb 23 16:56:04 CST 2022
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.userId
     *
     * @param userid the value for record.userId
     *
     * @mbg.generated Wed Feb 23 16:56:04 CST 2022
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.projectId
     *
     * @return the value of record.projectId
     *
     * @mbg.generated Wed Feb 23 16:56:04 CST 2022
     */
    public Integer getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.projectId
     *
     * @param projectid the value for record.projectId
     *
     * @mbg.generated Wed Feb 23 16:56:04 CST 2022
     */
    public void setProjectid(Integer projectid) {
        this.projectid = projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.operation
     *
     * @return the value of record.operation
     *
     * @mbg.generated Wed Feb 23 16:56:04 CST 2022
     */
    public String getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.operation
     *
     * @param operation the value for record.operation
     *
     * @mbg.generated Wed Feb 23 16:56:04 CST 2022
     */
    public void setOperation(String operation) {
        this.operation = operation == null ? null : operation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.operateDate
     *
     * @return the value of record.operateDate
     *
     * @mbg.generated Wed Feb 23 16:56:04 CST 2022
     */
    public Date getOperatedate() {
        return operatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.operateDate
     *
     * @param operatedate the value for record.operateDate
     *
     * @mbg.generated Wed Feb 23 16:56:04 CST 2022
     */
    public void setOperatedate(Date operatedate) {
        this.operatedate = operatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.operateResult
     *
     * @return the value of record.operateResult
     *
     * @mbg.generated Wed Feb 23 16:56:04 CST 2022
     */
    public String getOperateresult() {
        return operateresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.operateResult
     *
     * @param operateresult the value for record.operateResult
     *
     * @mbg.generated Wed Feb 23 16:56:04 CST 2022
     */
    public void setOperateresult(String operateresult) {
        this.operateresult = operateresult == null ? null : operateresult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.fileName
     *
     * @return the value of record.fileName
     *
     * @mbg.generated Wed Feb 23 16:56:04 CST 2022
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.fileName
     *
     * @param filename the value for record.fileName
     *
     * @mbg.generated Wed Feb 23 16:56:04 CST 2022
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }
}