package com.hlc.codeanalyzesystem.entity;

import java.util.ArrayList;
import java.util.List;

public class FileresultExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fileresult
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fileresult
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fileresult
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileresult
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    public FileresultExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileresult
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileresult
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileresult
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileresult
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileresult
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileresult
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileresult
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileresult
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileresult
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileresult
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fileresult
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andBelongtoIsNull() {
            addCriterion("belongTo is null");
            return (Criteria) this;
        }

        public Criteria andBelongtoIsNotNull() {
            addCriterion("belongTo is not null");
            return (Criteria) this;
        }

        public Criteria andBelongtoEqualTo(Integer value) {
            addCriterion("belongTo =", value, "belongto");
            return (Criteria) this;
        }

        public Criteria andBelongtoNotEqualTo(Integer value) {
            addCriterion("belongTo <>", value, "belongto");
            return (Criteria) this;
        }

        public Criteria andBelongtoGreaterThan(Integer value) {
            addCriterion("belongTo >", value, "belongto");
            return (Criteria) this;
        }

        public Criteria andBelongtoGreaterThanOrEqualTo(Integer value) {
            addCriterion("belongTo >=", value, "belongto");
            return (Criteria) this;
        }

        public Criteria andBelongtoLessThan(Integer value) {
            addCriterion("belongTo <", value, "belongto");
            return (Criteria) this;
        }

        public Criteria andBelongtoLessThanOrEqualTo(Integer value) {
            addCriterion("belongTo <=", value, "belongto");
            return (Criteria) this;
        }

        public Criteria andBelongtoIn(List<Integer> values) {
            addCriterion("belongTo in", values, "belongto");
            return (Criteria) this;
        }

        public Criteria andBelongtoNotIn(List<Integer> values) {
            addCriterion("belongTo not in", values, "belongto");
            return (Criteria) this;
        }

        public Criteria andBelongtoBetween(Integer value1, Integer value2) {
            addCriterion("belongTo between", value1, value2, "belongto");
            return (Criteria) this;
        }

        public Criteria andBelongtoNotBetween(Integer value1, Integer value2) {
            addCriterion("belongTo not between", value1, value2, "belongto");
            return (Criteria) this;
        }

        public Criteria andLinecountIsNull() {
            addCriterion("lineCount is null");
            return (Criteria) this;
        }

        public Criteria andLinecountIsNotNull() {
            addCriterion("lineCount is not null");
            return (Criteria) this;
        }

        public Criteria andLinecountEqualTo(Integer value) {
            addCriterion("lineCount =", value, "linecount");
            return (Criteria) this;
        }

        public Criteria andLinecountNotEqualTo(Integer value) {
            addCriterion("lineCount <>", value, "linecount");
            return (Criteria) this;
        }

        public Criteria andLinecountGreaterThan(Integer value) {
            addCriterion("lineCount >", value, "linecount");
            return (Criteria) this;
        }

        public Criteria andLinecountGreaterThanOrEqualTo(Integer value) {
            addCriterion("lineCount >=", value, "linecount");
            return (Criteria) this;
        }

        public Criteria andLinecountLessThan(Integer value) {
            addCriterion("lineCount <", value, "linecount");
            return (Criteria) this;
        }

        public Criteria andLinecountLessThanOrEqualTo(Integer value) {
            addCriterion("lineCount <=", value, "linecount");
            return (Criteria) this;
        }

        public Criteria andLinecountIn(List<Integer> values) {
            addCriterion("lineCount in", values, "linecount");
            return (Criteria) this;
        }

        public Criteria andLinecountNotIn(List<Integer> values) {
            addCriterion("lineCount not in", values, "linecount");
            return (Criteria) this;
        }

        public Criteria andLinecountBetween(Integer value1, Integer value2) {
            addCriterion("lineCount between", value1, value2, "linecount");
            return (Criteria) this;
        }

        public Criteria andLinecountNotBetween(Integer value1, Integer value2) {
            addCriterion("lineCount not between", value1, value2, "linecount");
            return (Criteria) this;
        }

        public Criteria andClasscountIsNull() {
            addCriterion("classCount is null");
            return (Criteria) this;
        }

        public Criteria andClasscountIsNotNull() {
            addCriterion("classCount is not null");
            return (Criteria) this;
        }

        public Criteria andClasscountEqualTo(Integer value) {
            addCriterion("classCount =", value, "classcount");
            return (Criteria) this;
        }

        public Criteria andClasscountNotEqualTo(Integer value) {
            addCriterion("classCount <>", value, "classcount");
            return (Criteria) this;
        }

        public Criteria andClasscountGreaterThan(Integer value) {
            addCriterion("classCount >", value, "classcount");
            return (Criteria) this;
        }

        public Criteria andClasscountGreaterThanOrEqualTo(Integer value) {
            addCriterion("classCount >=", value, "classcount");
            return (Criteria) this;
        }

        public Criteria andClasscountLessThan(Integer value) {
            addCriterion("classCount <", value, "classcount");
            return (Criteria) this;
        }

        public Criteria andClasscountLessThanOrEqualTo(Integer value) {
            addCriterion("classCount <=", value, "classcount");
            return (Criteria) this;
        }

        public Criteria andClasscountIn(List<Integer> values) {
            addCriterion("classCount in", values, "classcount");
            return (Criteria) this;
        }

        public Criteria andClasscountNotIn(List<Integer> values) {
            addCriterion("classCount not in", values, "classcount");
            return (Criteria) this;
        }

        public Criteria andClasscountBetween(Integer value1, Integer value2) {
            addCriterion("classCount between", value1, value2, "classcount");
            return (Criteria) this;
        }

        public Criteria andClasscountNotBetween(Integer value1, Integer value2) {
            addCriterion("classCount not between", value1, value2, "classcount");
            return (Criteria) this;
        }

        public Criteria andFunctioncountIsNull() {
            addCriterion("functionCount is null");
            return (Criteria) this;
        }

        public Criteria andFunctioncountIsNotNull() {
            addCriterion("functionCount is not null");
            return (Criteria) this;
        }

        public Criteria andFunctioncountEqualTo(Integer value) {
            addCriterion("functionCount =", value, "functioncount");
            return (Criteria) this;
        }

        public Criteria andFunctioncountNotEqualTo(Integer value) {
            addCriterion("functionCount <>", value, "functioncount");
            return (Criteria) this;
        }

        public Criteria andFunctioncountGreaterThan(Integer value) {
            addCriterion("functionCount >", value, "functioncount");
            return (Criteria) this;
        }

        public Criteria andFunctioncountGreaterThanOrEqualTo(Integer value) {
            addCriterion("functionCount >=", value, "functioncount");
            return (Criteria) this;
        }

        public Criteria andFunctioncountLessThan(Integer value) {
            addCriterion("functionCount <", value, "functioncount");
            return (Criteria) this;
        }

        public Criteria andFunctioncountLessThanOrEqualTo(Integer value) {
            addCriterion("functionCount <=", value, "functioncount");
            return (Criteria) this;
        }

        public Criteria andFunctioncountIn(List<Integer> values) {
            addCriterion("functionCount in", values, "functioncount");
            return (Criteria) this;
        }

        public Criteria andFunctioncountNotIn(List<Integer> values) {
            addCriterion("functionCount not in", values, "functioncount");
            return (Criteria) this;
        }

        public Criteria andFunctioncountBetween(Integer value1, Integer value2) {
            addCriterion("functionCount between", value1, value2, "functioncount");
            return (Criteria) this;
        }

        public Criteria andFunctioncountNotBetween(Integer value1, Integer value2) {
            addCriterion("functionCount not between", value1, value2, "functioncount");
            return (Criteria) this;
        }

        public Criteria andVariablecountIsNull() {
            addCriterion("variableCount is null");
            return (Criteria) this;
        }

        public Criteria andVariablecountIsNotNull() {
            addCriterion("variableCount is not null");
            return (Criteria) this;
        }

        public Criteria andVariablecountEqualTo(Integer value) {
            addCriterion("variableCount =", value, "variablecount");
            return (Criteria) this;
        }

        public Criteria andVariablecountNotEqualTo(Integer value) {
            addCriterion("variableCount <>", value, "variablecount");
            return (Criteria) this;
        }

        public Criteria andVariablecountGreaterThan(Integer value) {
            addCriterion("variableCount >", value, "variablecount");
            return (Criteria) this;
        }

        public Criteria andVariablecountGreaterThanOrEqualTo(Integer value) {
            addCriterion("variableCount >=", value, "variablecount");
            return (Criteria) this;
        }

        public Criteria andVariablecountLessThan(Integer value) {
            addCriterion("variableCount <", value, "variablecount");
            return (Criteria) this;
        }

        public Criteria andVariablecountLessThanOrEqualTo(Integer value) {
            addCriterion("variableCount <=", value, "variablecount");
            return (Criteria) this;
        }

        public Criteria andVariablecountIn(List<Integer> values) {
            addCriterion("variableCount in", values, "variablecount");
            return (Criteria) this;
        }

        public Criteria andVariablecountNotIn(List<Integer> values) {
            addCriterion("variableCount not in", values, "variablecount");
            return (Criteria) this;
        }

        public Criteria andVariablecountBetween(Integer value1, Integer value2) {
            addCriterion("variableCount between", value1, value2, "variablecount");
            return (Criteria) this;
        }

        public Criteria andVariablecountNotBetween(Integer value1, Integer value2) {
            addCriterion("variableCount not between", value1, value2, "variablecount");
            return (Criteria) this;
        }

        public Criteria andLongestclassIsNull() {
            addCriterion("longestClass is null");
            return (Criteria) this;
        }

        public Criteria andLongestclassIsNotNull() {
            addCriterion("longestClass is not null");
            return (Criteria) this;
        }

        public Criteria andLongestclassEqualTo(String value) {
            addCriterion("longestClass =", value, "longestclass");
            return (Criteria) this;
        }

        public Criteria andLongestclassNotEqualTo(String value) {
            addCriterion("longestClass <>", value, "longestclass");
            return (Criteria) this;
        }

        public Criteria andLongestclassGreaterThan(String value) {
            addCriterion("longestClass >", value, "longestclass");
            return (Criteria) this;
        }

        public Criteria andLongestclassGreaterThanOrEqualTo(String value) {
            addCriterion("longestClass >=", value, "longestclass");
            return (Criteria) this;
        }

        public Criteria andLongestclassLessThan(String value) {
            addCriterion("longestClass <", value, "longestclass");
            return (Criteria) this;
        }

        public Criteria andLongestclassLessThanOrEqualTo(String value) {
            addCriterion("longestClass <=", value, "longestclass");
            return (Criteria) this;
        }

        public Criteria andLongestclassLike(String value) {
            addCriterion("longestClass like", value, "longestclass");
            return (Criteria) this;
        }

        public Criteria andLongestclassNotLike(String value) {
            addCriterion("longestClass not like", value, "longestclass");
            return (Criteria) this;
        }

        public Criteria andLongestclassIn(List<String> values) {
            addCriterion("longestClass in", values, "longestclass");
            return (Criteria) this;
        }

        public Criteria andLongestclassNotIn(List<String> values) {
            addCriterion("longestClass not in", values, "longestclass");
            return (Criteria) this;
        }

        public Criteria andLongestclassBetween(String value1, String value2) {
            addCriterion("longestClass between", value1, value2, "longestclass");
            return (Criteria) this;
        }

        public Criteria andLongestclassNotBetween(String value1, String value2) {
            addCriterion("longestClass not between", value1, value2, "longestclass");
            return (Criteria) this;
        }

        public Criteria andLongestfunctionIsNull() {
            addCriterion("longestFunction is null");
            return (Criteria) this;
        }

        public Criteria andLongestfunctionIsNotNull() {
            addCriterion("longestFunction is not null");
            return (Criteria) this;
        }

        public Criteria andLongestfunctionEqualTo(String value) {
            addCriterion("longestFunction =", value, "longestfunction");
            return (Criteria) this;
        }

        public Criteria andLongestfunctionNotEqualTo(String value) {
            addCriterion("longestFunction <>", value, "longestfunction");
            return (Criteria) this;
        }

        public Criteria andLongestfunctionGreaterThan(String value) {
            addCriterion("longestFunction >", value, "longestfunction");
            return (Criteria) this;
        }

        public Criteria andLongestfunctionGreaterThanOrEqualTo(String value) {
            addCriterion("longestFunction >=", value, "longestfunction");
            return (Criteria) this;
        }

        public Criteria andLongestfunctionLessThan(String value) {
            addCriterion("longestFunction <", value, "longestfunction");
            return (Criteria) this;
        }

        public Criteria andLongestfunctionLessThanOrEqualTo(String value) {
            addCriterion("longestFunction <=", value, "longestfunction");
            return (Criteria) this;
        }

        public Criteria andLongestfunctionLike(String value) {
            addCriterion("longestFunction like", value, "longestfunction");
            return (Criteria) this;
        }

        public Criteria andLongestfunctionNotLike(String value) {
            addCriterion("longestFunction not like", value, "longestfunction");
            return (Criteria) this;
        }

        public Criteria andLongestfunctionIn(List<String> values) {
            addCriterion("longestFunction in", values, "longestfunction");
            return (Criteria) this;
        }

        public Criteria andLongestfunctionNotIn(List<String> values) {
            addCriterion("longestFunction not in", values, "longestfunction");
            return (Criteria) this;
        }

        public Criteria andLongestfunctionBetween(String value1, String value2) {
            addCriterion("longestFunction between", value1, value2, "longestfunction");
            return (Criteria) this;
        }

        public Criteria andLongestfunctionNotBetween(String value1, String value2) {
            addCriterion("longestFunction not between", value1, value2, "longestfunction");
            return (Criteria) this;
        }

        public Criteria andClasslistIsNull() {
            addCriterion("classList is null");
            return (Criteria) this;
        }

        public Criteria andClasslistIsNotNull() {
            addCriterion("classList is not null");
            return (Criteria) this;
        }

        public Criteria andClasslistEqualTo(String value) {
            addCriterion("classList =", value, "classlist");
            return (Criteria) this;
        }

        public Criteria andClasslistNotEqualTo(String value) {
            addCriterion("classList <>", value, "classlist");
            return (Criteria) this;
        }

        public Criteria andClasslistGreaterThan(String value) {
            addCriterion("classList >", value, "classlist");
            return (Criteria) this;
        }

        public Criteria andClasslistGreaterThanOrEqualTo(String value) {
            addCriterion("classList >=", value, "classlist");
            return (Criteria) this;
        }

        public Criteria andClasslistLessThan(String value) {
            addCriterion("classList <", value, "classlist");
            return (Criteria) this;
        }

        public Criteria andClasslistLessThanOrEqualTo(String value) {
            addCriterion("classList <=", value, "classlist");
            return (Criteria) this;
        }

        public Criteria andClasslistLike(String value) {
            addCriterion("classList like", value, "classlist");
            return (Criteria) this;
        }

        public Criteria andClasslistNotLike(String value) {
            addCriterion("classList not like", value, "classlist");
            return (Criteria) this;
        }

        public Criteria andClasslistIn(List<String> values) {
            addCriterion("classList in", values, "classlist");
            return (Criteria) this;
        }

        public Criteria andClasslistNotIn(List<String> values) {
            addCriterion("classList not in", values, "classlist");
            return (Criteria) this;
        }

        public Criteria andClasslistBetween(String value1, String value2) {
            addCriterion("classList between", value1, value2, "classlist");
            return (Criteria) this;
        }

        public Criteria andClasslistNotBetween(String value1, String value2) {
            addCriterion("classList not between", value1, value2, "classlist");
            return (Criteria) this;
        }

        public Criteria andFunctionlistIsNull() {
            addCriterion("functionList is null");
            return (Criteria) this;
        }

        public Criteria andFunctionlistIsNotNull() {
            addCriterion("functionList is not null");
            return (Criteria) this;
        }

        public Criteria andFunctionlistEqualTo(String value) {
            addCriterion("functionList =", value, "functionlist");
            return (Criteria) this;
        }

        public Criteria andFunctionlistNotEqualTo(String value) {
            addCriterion("functionList <>", value, "functionlist");
            return (Criteria) this;
        }

        public Criteria andFunctionlistGreaterThan(String value) {
            addCriterion("functionList >", value, "functionlist");
            return (Criteria) this;
        }

        public Criteria andFunctionlistGreaterThanOrEqualTo(String value) {
            addCriterion("functionList >=", value, "functionlist");
            return (Criteria) this;
        }

        public Criteria andFunctionlistLessThan(String value) {
            addCriterion("functionList <", value, "functionlist");
            return (Criteria) this;
        }

        public Criteria andFunctionlistLessThanOrEqualTo(String value) {
            addCriterion("functionList <=", value, "functionlist");
            return (Criteria) this;
        }

        public Criteria andFunctionlistLike(String value) {
            addCriterion("functionList like", value, "functionlist");
            return (Criteria) this;
        }

        public Criteria andFunctionlistNotLike(String value) {
            addCriterion("functionList not like", value, "functionlist");
            return (Criteria) this;
        }

        public Criteria andFunctionlistIn(List<String> values) {
            addCriterion("functionList in", values, "functionlist");
            return (Criteria) this;
        }

        public Criteria andFunctionlistNotIn(List<String> values) {
            addCriterion("functionList not in", values, "functionlist");
            return (Criteria) this;
        }

        public Criteria andFunctionlistBetween(String value1, String value2) {
            addCriterion("functionList between", value1, value2, "functionlist");
            return (Criteria) this;
        }

        public Criteria andFunctionlistNotBetween(String value1, String value2) {
            addCriterion("functionList not between", value1, value2, "functionlist");
            return (Criteria) this;
        }

        public Criteria andVariablelistIsNull() {
            addCriterion("variableList is null");
            return (Criteria) this;
        }

        public Criteria andVariablelistIsNotNull() {
            addCriterion("variableList is not null");
            return (Criteria) this;
        }

        public Criteria andVariablelistEqualTo(String value) {
            addCriterion("variableList =", value, "variablelist");
            return (Criteria) this;
        }

        public Criteria andVariablelistNotEqualTo(String value) {
            addCriterion("variableList <>", value, "variablelist");
            return (Criteria) this;
        }

        public Criteria andVariablelistGreaterThan(String value) {
            addCriterion("variableList >", value, "variablelist");
            return (Criteria) this;
        }

        public Criteria andVariablelistGreaterThanOrEqualTo(String value) {
            addCriterion("variableList >=", value, "variablelist");
            return (Criteria) this;
        }

        public Criteria andVariablelistLessThan(String value) {
            addCriterion("variableList <", value, "variablelist");
            return (Criteria) this;
        }

        public Criteria andVariablelistLessThanOrEqualTo(String value) {
            addCriterion("variableList <=", value, "variablelist");
            return (Criteria) this;
        }

        public Criteria andVariablelistLike(String value) {
            addCriterion("variableList like", value, "variablelist");
            return (Criteria) this;
        }

        public Criteria andVariablelistNotLike(String value) {
            addCriterion("variableList not like", value, "variablelist");
            return (Criteria) this;
        }

        public Criteria andVariablelistIn(List<String> values) {
            addCriterion("variableList in", values, "variablelist");
            return (Criteria) this;
        }

        public Criteria andVariablelistNotIn(List<String> values) {
            addCriterion("variableList not in", values, "variablelist");
            return (Criteria) this;
        }

        public Criteria andVariablelistBetween(String value1, String value2) {
            addCriterion("variableList between", value1, value2, "variablelist");
            return (Criteria) this;
        }

        public Criteria andVariablelistNotBetween(String value1, String value2) {
            addCriterion("variableList not between", value1, value2, "variablelist");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fileresult
     *
     * @mbg.generated do_not_delete_during_merge Wed Mar 02 10:36:24 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fileresult
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}