package com.hlc.codeanalyzesystem.entity;

public class Fileresult {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileresult.id
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileresult.name
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileresult.belongTo
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    private Integer belongto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileresult.lineCount
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    private Integer linecount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileresult.classCount
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    private Integer classcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileresult.functionCount
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    private Integer functioncount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileresult.variableCount
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    private Integer variablecount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileresult.longestClass
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    private String longestclass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileresult.longestFunction
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    private String longestfunction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileresult.classList
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    private String classlist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileresult.functionList
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    private String functionlist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileresult.variableList
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    private String variablelist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileresult.functionVariable
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    private String functionvariable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileresult.id
     *
     * @return the value of fileresult.id
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileresult.id
     *
     * @param id the value for fileresult.id
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileresult.name
     *
     * @return the value of fileresult.name
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileresult.name
     *
     * @param name the value for fileresult.name
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileresult.belongTo
     *
     * @return the value of fileresult.belongTo
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    public Integer getBelongto() {
        return belongto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileresult.belongTo
     *
     * @param belongto the value for fileresult.belongTo
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    public void setBelongto(Integer belongto) {
        this.belongto = belongto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileresult.lineCount
     *
     * @return the value of fileresult.lineCount
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    public Integer getLinecount() {
        return linecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileresult.lineCount
     *
     * @param linecount the value for fileresult.lineCount
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    public void setLinecount(Integer linecount) {
        this.linecount = linecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileresult.classCount
     *
     * @return the value of fileresult.classCount
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    public Integer getClasscount() {
        return classcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileresult.classCount
     *
     * @param classcount the value for fileresult.classCount
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    public void setClasscount(Integer classcount) {
        this.classcount = classcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileresult.functionCount
     *
     * @return the value of fileresult.functionCount
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    public Integer getFunctioncount() {
        return functioncount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileresult.functionCount
     *
     * @param functioncount the value for fileresult.functionCount
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    public void setFunctioncount(Integer functioncount) {
        this.functioncount = functioncount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileresult.variableCount
     *
     * @return the value of fileresult.variableCount
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    public Integer getVariablecount() {
        return variablecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileresult.variableCount
     *
     * @param variablecount the value for fileresult.variableCount
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    public void setVariablecount(Integer variablecount) {
        this.variablecount = variablecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileresult.longestClass
     *
     * @return the value of fileresult.longestClass
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    public String getLongestclass() {
        return longestclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileresult.longestClass
     *
     * @param longestclass the value for fileresult.longestClass
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    public void setLongestclass(String longestclass) {
        this.longestclass = longestclass == null ? null : longestclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileresult.longestFunction
     *
     * @return the value of fileresult.longestFunction
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    public String getLongestfunction() {
        return longestfunction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileresult.longestFunction
     *
     * @param longestfunction the value for fileresult.longestFunction
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    public void setLongestfunction(String longestfunction) {
        this.longestfunction = longestfunction == null ? null : longestfunction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileresult.classList
     *
     * @return the value of fileresult.classList
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    public String getClasslist() {
        return classlist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileresult.classList
     *
     * @param classlist the value for fileresult.classList
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    public void setClasslist(String classlist) {
        this.classlist = classlist == null ? null : classlist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileresult.functionList
     *
     * @return the value of fileresult.functionList
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    public String getFunctionlist() {
        return functionlist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileresult.functionList
     *
     * @param functionlist the value for fileresult.functionList
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    public void setFunctionlist(String functionlist) {
        this.functionlist = functionlist == null ? null : functionlist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileresult.variableList
     *
     * @return the value of fileresult.variableList
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    public String getVariablelist() {
        return variablelist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileresult.variableList
     *
     * @param variablelist the value for fileresult.variableList
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    public void setVariablelist(String variablelist) {
        this.variablelist = variablelist == null ? null : variablelist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileresult.functionVariable
     *
     * @return the value of fileresult.functionVariable
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    public String getFunctionvariable() {
        return functionvariable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileresult.functionVariable
     *
     * @param functionvariable the value for fileresult.functionVariable
     *
     * @mbg.generated Wed Mar 02 10:36:24 CST 2022
     */
    public void setFunctionvariable(String functionvariable) {
        this.functionvariable = functionvariable == null ? null : functionvariable.trim();
    }
}